In [3]:
import numpy as np

a = np.array([1, 2, 3,4,5])
print('Boyut:', a.shape)
print('Veri Tipi:', a.dtype)
print('Eleman Sayısı:', a.ndim)
print('Boyut Sayısı:', a.size)

Boyut: (5,)
Veri Tipi: int64
Eleman Sayısı: 1
Boyut Sayısı: 5


In [12]:

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("İki boyutlu arrayin boyutu:", arr2.ndim)
print("İki boyutlu arrayin eleman sayısı:", arr2.size)
print("İki boyutlu arrayin şekli:", arr2.shape)

arr3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print("\nÜç boyutlu arrayin boyutu:", arr3.ndim)
print("Üç boyutlu arrayin eleman sayısı:", arr3.size)
print("Üç boyutlu arrayin şekli:", arr3.shape)

print("\nİki boyutlu arrayin [2,4] elemanı:", arr2[1, 2])
print("İki boyutlu arrayin ilk satırı:", arr2[0, :])


print("\nÜç boyutlu arrayin [1,0,1] elemanı:", arr3[1, 0, 1])
print("Üç boyutlu arrayin ilk 'katmanı':", arr3[0, :, :])

İki boyutlu arrayin boyutu: 2
İki boyutlu arrayin eleman sayısı: 6
İki boyutlu arrayin şekli: (2, 3)

Üç boyutlu arrayin boyutu: 3
Üç boyutlu arrayin eleman sayısı: 12
Üç boyutlu arrayin şekli: (2, 2, 3)

İki boyutlu arrayin [2,4] elemanı: 6
İki boyutlu arrayin ilk satırı: [1 2 3]

Üç boyutlu arrayin [1,0,1] elemanı: 8
Üç boyutlu arrayin ilk 'katmanı': [[1 2 3]
 [4 5 6]]


In [13]:
arr0 = np.zeros((2, 3), dtype=int)
print("Sıfırlardan oluşan array:\n", arr0)

arr1 = np.ones((2, 3), dtype=int)
print("Birlerden oluşan array:\n", arr1)

vstack = np.vstack((arr0, arr1))
print("Satır bazında birleştirilmiş array:\n", vstack)

hstack = np.hstack((arr0, arr1))
print("Sütun bazında birleştirilmiş array:\n", hstack)


Sıfırlardan oluşan array:
 [[0 0 0]
 [0 0 0]]
Birlerden oluşan array:
 [[1 1 1]
 [1 1 1]]
Satır bazında birleştirilmiş array:
 [[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]
Sütun bazında birleştirilmiş array:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]]
